name: bioinfo2 # name of the environment created
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mosdepth
  - prodigal
  - python=3.6.15
  - bwa=0.7.18
  - samtools=1.3.1
  - freebayes=1.1.0
  - picard=2.20.4
  - bedtools=2.31.1
  - trimmomatic=0.39
  - fastqc=0.12.1
  - vcflib=1.0.0_rc1
  - numpy=1.19.5
  - bcftools
  - snpeff